w3f/General-Grants-Program

grants/grants.md

Adjust Apply here.
Minor language / layout changes.
###

Fixes and changes.

---

grants/speculative/polkadot_sofia.md

Polkadot Meetup - Sofia, Bulgaria

---

grants/speculative/speckleos.md

###
We are building a universal user interface for Polkadot, Substrate and Web 3. This involves three parts:
1.	Speckle Browser: a front-end browser specialized for a web of connected chains;
2.	Speckle Parachain: a back-end parachain that handles identity, account management and communication; and
3.	Speckle Box: the speckle-ui framework for substrate-based chains.

Universal User Interface for Polkadot and Substrate (Speckle Browser)

---

grants/speculative/Enzyme.md

###
We intend to create a Chrome Extension DApp Wallet. Similar to Metamask, this wallet will be compatible with substrate core and configurable to the modules used by any standard parachain. When a user creates a parachain, they will very quickly have a professionally made, well-tested Chrome Extension DApp Wallet. This can also interoperate between all substrate chains.

Enzyme - Chrome Extension DApp Wallet for Substrate 

---

grants/speculative/robotics_in_polkadot.md

###
We a building Robotics oriented parachain for Polkadot. Creating a bridge between the Polkadot client and the robotics frameworks helps to involve robotics developers to use blockchain and Polkadot in particular.

Robotics integration in Polkadot

---

grants/speculative/MixBytes_Tank.md

###
This grant application supports the development of MixBytes Tank - a tool for blockchain stability and performance benchmarking. It will allow to identify bottlenecks and pain points of the project, then report the results and offer recommendations. The tool will be suitable for multiple benchmarking of new Substrate versions.
* We will require 3 months to complete this project.
* We intend to have 2 developers full-time and 2 part-time.

MixBytes Tank - blockchain stability and performance benchmarking tool

---

grants/speculative/GunClear.md

###
As part of building the GunClear application, we are planning on leveraging the Substrate framework to build a Plasma client, as well as building in our zk-SNARKs designs and working on an i2p transport layer for libp2p long-term.

GunClear Grant Application

---

grants/targeted/messaging.md

###
This grant application supports the development of a decentralized and privacy-preserving messaging protocol called HOPR. Within the framework of this grant application Validity Labs AG will be able to finalize a first specification, implementation of the protocol and assess how HOPR could improve the Substrate & Polkadot stack and how a dedicated HOPR parachain could benefit the development of the protocol.

HOPR - incentivized and privacy-preserving messaging protocol

---

grants/targeted/polkadot_Substrate_Java_API.md

Our team will develop the Polkadot/Substrate Java API.Java APIs around Polkadot and any Substrate-based chain RPC calls. It is dynamically generated based on what the Substrate runtime provides in terms of metadata.
###
Our team will develop the Polkadot/Substrate Java API.Java APIs around Polkadot and any Substrate-based chain RPC calls. It is dynamically generated based on what the Substrate runtime provides in terms of metadata.

polkadot_Substrate_Java_API

---

grants/speculative/centrifuge_go_substrate_rpc_client.md

###
We are building a Substrate RPC client in Go. The client will be modelled after polkadot-js/api. We want to lower the friction of using Go with Substrate-based chains and believe this broadening of client libraries will benefit many teams in the community. On top of that, a Go Substrate RPC client will give many more developers easy access to integrate existing Go applications with new Substrate chains.

Go Substrate RPC Client

---

grants/speculative/vscode_plugin.md

vscode plugin

---

grants/speculative/litentry.md

###
Polkadot Runtime Modules and corresponding UIs: Identity
Litentry is a second layer protocol and infrastructure based on Substrate. It focuses on Identity of person and IoT devices, and the authorization and permissions granted by the Person or IoT devices.
Details please see [our blog](https://www.litentry.com/post/litentry-introduction) and [the pitch presentation](https://drive.google.com/file/d/1-mesEZV5eoRW_dP3MZwbZPUaqNPtMoxd/view?usp=sharing)

Identity Second Layer, Polkadot Runtime Module and UI

---

grants/targeted/wasm-verification.md

- [ x ] an RFP response
###
- [ x ] Public with private finances
This grant proposal is in response to the following RFP: <https://medium.com/polkadot-network/apply-to-audit-polkadots-runtime-86c988ced31b>.
We propose formally verifying the generated Wasm code of a core part of the Polkadot module system (in Rust) to guard against code generation and correctness bugs. This provides security auditors with a complete specification of the behaviors of the generated Wasm.
The verification artifacts (K specifications) can be integrated directly into Polkadot’s CI system so that on changes to behavior action must be taken to either fix the code or update the specification.
- [ x ] The …

grants/targeted/wasm-verification: RVs initial grant application

---

grants/speculative/Vuejs_ui-components.md

###
We are going to build Vue.js components for Polkadot and Substrate ecosystem. 
Inspiration is to reimplement existing [React components](https://polkadot.js.org/ui/).
It will help Vue.js developers to build their own app-modules for frontend apps easier. 
[Experienced building web-based Subkey in Vue.js](https://subkey.netlify.com/)

Vue.js ui components

---

grants/speculative/pLIBRA.md

###
pLIBRA is a privacy-preserving Libra powered by Private Contract on Polkadot. We aim to protect the privacy of Libra users. More specifically we will create:
- A bridge connecting Polkadot and Libra
- A privacy-preserving token on Polkadot for Libra users
- A privacy-preserving DApp ecosystem better than Calibra

pLIBRA grants proposal

---

grants/speculative/Subsocial.md

###
**SubSocial** is a Substrate runtime module (SRML) with UI that allows anyone to launch their own decentralized censorship-resistant social network aka community. You can think of this as decentralized versions of Reddit, Stack Exchange or Medium, where every community run their own chain. At the same time, users of these decentralized communities should be able to share their reputation, transfer coins and other values from one community to another via Polkadot relay.
- Create/edit blogs and posts.
- Comment posts, edit own comments.
- Upvote/downvote posts and comments.
- Save text content on IPFS.
- Account's reputation based on its activity: posts, comments, and votes.
- Activity stream for blogs and accounts that …

Subsocial - SRML and UI for decentralized communities

---

grants/accepted_grant_applications.md

I added a list of accepted grant applications, but I haven't link to it in another document yet.

Add List of Accepted Grant Applications

---

grants/grants.md

removing community grants

---

grants/speculative/python_substrate_api.md

###
This project develops a Python Substrate API client and libraries for general use. The client will be modeled after polkadot-js/api.
WEB3SCAN is on an ongoing mission of building the Polkascan Multi-chain Explorer. With our first wave grant nearing completion, a number of Python-libraries were developed, such as: `Py-Scale-Codec` and `Py-Substrate-Interface`. These libraries have been limited in scope to match the requirements of our block explorer use-case. This project extends and feature-completes these two libraries for general use.
WEB3SCAN believes in the success of Substrate and Polkadot, we are highly invested in the ecosystem from day one and are highly invested in Python. This project aims to lower the …

Python Substrate API

---

grants/speculative/polkadot_overview.md

###
We are going to build a validators explorer for Polkadot Network. It will contain the list of active validators, their information and statistic.
It will help the Polkadot users to see the summarized data about validators in one place.

Polkadot Overview - Validators Explorer

---

grants/speculative/panic_by_simply_vc.md

###
P.A.N.I.C. by Simply VC is a monitoring and alerting solution for validators that keeps an eye on one or more nodes and swiftly sends relevant alerts via the multiple alerting channels supported. P.A.N.I.C. is [currently open-source](https://github.com/SimplyVC/panic) for Cosmos validators and we wish to extend it's alerting to Substrate-based nodes.
(to be included in Google Form)

P.A.N.I.C. by Simply VC

---

grants/speculative/ink_playground.md

- Speculative (use this by default)
###
- Public (fully)
ink! playground is a browser IDE for Substrate's smart contract.

ink! playground

---

grants/speculative/PolkAlert.md

###
Node monitoring tool, which alerts validators and their nominators if some malicious staking (in)activity occured. By decreasing their reaction time for fix or replacing their funds, Polkalert is an essential tool for every responsible validator and nominator.

Validator node monitoring

---

grants/speculative/substrate x (prometheus + grafana) by B-Harvest.md

substrate x (prometheus + grafana) by B-Harvest

---

grants/speculative/ink-remix-plugin.md

###
Implementing fully-fledged IDE with React frontend inside Remix (as a remix plugin) and backend (Node.js) with websocket connection between the two. 
The backend will then connect to multiple instances of ink! CLI running on multiple hosts all managed by Kubernetes. 
The whole backend and CLI part would be built on kubernetes with autoscaling as the most performance consuming part are ink! CLI’s themselves. Both backend and ink! CLI will be dockerized. 
Standard REST API requests can’t be used here as timeout would often happen on long build times and that is not a feasible solution. Usage of websockets solves this problem.
Further on deploy …

ink! Remix Plugin

---

grants/speculative/polkadot_js_chrome_extension.md

###
- [] Public with private finances
We want do propose 2 improvements to the Polkadot.{js} browser extension.
1. A substantial UI/UX overhaul of the extension.
2. Improved account management, especially adding account derivation.

Polkadot.{js} extension improvements

---

grants/speculative/Speckle Application.md

###
Speckle OS is building a universal user interface for Polkadot, Substrate and Web 3. This involves three parts:
1. Speckle Browser: a front-end browser extension that handles account management and dApp interactivity across Substrate chains;
2. Speckle Parachain: a back-end parachain that handles identity management and abstracts away complex account identifiers; 
3. Speckle Box: the speckle-ui framework for substrate-based chains.

Speckle OS - V2 of Browser Extension

---

grants/speculative/archipel.md

###
We want to build a solution to resolve high availability problem of Validator nodes in PoS using DAppNodes as an infrastructure layer. 
We plan to create the federation feature for DAppNode using Substrate framework for synchronization and orchestration.

Archipel - Highly available validators on light infrastructure

---

grants/targeted/datdot.md

grant application for datdot

---

grants/speculative/PolkaHub.md

###
This proposal features “Platform-as-a-Service (PaaS) for Substrate Nodes”: inspired by Heroku, aiming to create a managed container system, with one-click services for deploying and running different parachain. The proposed system enables automatic updates and resource management for running nodes, additionally providing templates for launching parachains.
[Read the Full Proposal →](https://github.com/akropolisio/Web3-collaboration/blob/master/grants/speculative/PolkaHub.md)

PolkaHub - Scalable Blockchain Infrastructure

---

grants/speculative/sr25519_port.md

###
We will deliver SR25519 library implemented in pure C as well as C# that is capable of producing a valid signature and validating a signature.

Sr25519 port

---

grants/targeted/predictive_performance_management_runtime_module.md

###
This grant application supports the development of a Decentralized Service Governance platform and network of Service-Level Agreements (SLA) called Stacktical.

Stacktical W3F Grant Application

---

grants/speculative/PlasmChian.md

###
Plasm Network is a scalable DApps platform on Polkadot. We plan to implement OVM, optimistic virtual machine on Plasm network. OVM is a virtual machine that is designed to support all layer2 protocols. The most important thing is that OVM can be a unification of all layer2 solutions. This means Plasm will be not only for Plasma but also for other layer2 scaling solutions such as Lightning Network and Raiden Network (State Channel). We try to implement all layer2 solutions on Polkadot.

Plasm Chain. OVM implementation. 

---

grants/targeted/PolkaWorld second grant application.md
grants/targeted/PolkaWorld.md

###
PolkaWorld is a Polkadot Chinese community founded in June 2019 and co-sponsored by the global blockchain knowledge community HashBang and the first chain in substrate ChainX. It provides a community for Polkafans and developers for communicating and learning.  Also PolkaWorld will help building the Polkadot Eco.

PolkaWorld

---

grants/accepted_grant_applications.md

Update URLs of Subsocial project (wave 3)

Update URLs of Subsocial project (wave 3)

---

grants/accepted_grant_applications.md

We recently changed our company's name from Staked to Stake Technologies. Thanks!

Changed our name: Staked to Stake Technologies

---

grants/grant_application_template.md

I donno if the second sentence is friendly enough, so feel free to drop it.

Ask for commits

---

grants/speculative/crawler.md

###
Build a standalone Polkadot network crawler to scan currently available nodes and saving details in external storage for further analysis or visualization.
The crawler is going to implement a subset of Polkadot p2p protocol to connect to nodes it can find and gather any additional information that can be fetched by requesting a connected node. I.e., current height, blocks, genesis, node software, IP address, and so forth. Gathered details a supposed to be stored in a database (for example, MySQL), and can be accessed by a 3rd party software for analysis.

Network Crawler

---

grants/speculative/bifrost_network.md

###
The Bifrost EOS interoperable bridge is a substrate-developed project that combines SPV client and multi-signature mechanisms to build a secure, flexible, and scalable cross-chain without modifying the core functionality of the parent chain. We also envisioned a version in which the parent and side chains are SPV clients of each other. 
This version is more distributed and safer, but it is costly and difficult to implement. The current approach not only allows the user's assets to be chained, but also the staking benefits of the parent chain. In the future, it can also support any operation across the chain for true interoperability.
[Read more →
](https://github.com/bifrost-codes/Web3-collaboration/blob/master/grants/ …

Bifrost EOS Interoperable Bridge

---

grants/speculative/polkascan_account_module.md

###
This project extends Polkascan with an enriched `account`-module. In its current form `accounts` have no support for the identity-pallet, have limited attributes, have limited associated entities and only support balances on the `account`-detail page. This project enriches the `account`-entity and thus provides a more complete picture of an account's state (identity, attributes and balances) and activities (associated events/extrinsics) as defined in the Kusama-CC3 runtime. The intended architecture is sufficiently general purpose to provide similar functions to other Substrate-based blockchain.
1. Identity: provide support for the `identity`-pallet.
2. Attributes: addition of account attributes and account …

Grant Apllication: Polkascan Account Module

---

grants/speculative/lunie.md

###
[Lunie](https://lunie.io) is one of the top staking and governance platforms for proof of stake blockchains. We'd like to add support for Kusama and Polkadot to our iOS, Android, and web applications. Support would include integration with the [Ledger Nano app](https://github.com/ZondaX/ledger-polkadot) and our [Lunie browser extension](https://chrome.google.com/webstore/detail/lunie-browser-extension/hbaijkfbhhdhhjdfbpdafkjimohblhgf) — as well as support for key management, portfolio management, and staking. We'd also like to include guides for how these things work inside the Lunie apps.

Lunie + Polkadot Grant Application

---

grants/speculative/encointer-testnet.md

###
The Encointer Association (EA) plans to develop an Encointer testnet named “Cantillon” ([spec](https://github.com/encointer/encointer-node/blob/master/doc/TESTNET_SPECIFICATION.md)). This testnet shall become a parachain to Kusama once Kusama is ready to host parachains.
The goal of the Cantillon Testnet is to deploy a [SubstraTEE](https://github.com/scs/substraTEE)-based PoA Blockchain that allows to bootstrap local currencies and take out daily Unique-Proof-of-Personhood ceremonies as defined in the encointer [whitepaper](https://github.com/encointer/whitepaper/blob/master/encointer_whitepaper.pdf). 
A mobile phone app that allows to perform key signing meetups has already been developed for …

Encointer testnet

---

grants/speculative/ewasm_and_toolchain.md

###
Second State proposes to create an optimized implementation of the next-gen Ethereum Virtual Machine (known as Ethereum Flavored WebAssembly, or Ewasm) and it's related compiler/optimizer toolchain. It will then make the Ewasm VM available as a Substrate runtime module library (SRML). This work will enable Substrate-based blockchains to leverage the large Ethereum developer ecosystem, and execute current and future Ethereum smart contracts out of the box.

Second State proposal

---

grants/speculative/metamask-plugin-polkadot.md

###
Implementing Metamask plugin (snap) to interact with Polkadot dapps and provide simple onboarding of Ethereum users.

Metamask plugin for Polkadot

---

grants/speculative/multisignature_implementation.md
grants/speculative/vscode_plugin.md

Multisignature Implementation

---

grants/speculative/SubstrateIDE.md

###
We would provide a graphical integrated development environment (IDE) for developing substrate-based blockchains on all major operating systems. By integrating numerous tools into a graphical interface, we believe Substrate IDE can help developers improve their efficiency substantially throughout the entire development process. Key features of Substrate IDE will include code editor, compiler, substrate node manager, debug tools to interact with substrate nodes, etc.

Substrate IDE

---

grants/speculative/KILT_AnonymousCredentials.md

###
Anonymous Credentials enable entities to obtain revocable credentials from trusted attesters (issuers) and show (some properties of) these credentials to multiple verifiers. The anonymisation ensures that multiple verifiers are unable to track a specific credential presenter entity by correlating the presenter's identity through colluding (sharing data) with each other.
The goal of the project is to extend the set of tools that enable privacy in the Polkadot ecosystem and web3 by developing the necessary integrations of the [Gabi library](https://github.com/privacybydesign/gabi) into the KILT/Substrate/Polkadot API stack. Completing this endeavor will enable the Substrate/Polkadot ecosystem to effortlessly use …

Submit speculative KILT AC grant application

---

grants/speculative/crust.md

###
Crust implements the incentive layer protocol for decentralized storage. It is adaptable to multiple storage layer protocols such as IPFS, and provides support for the application layer. Crust's architecture also has the capability of supporting a decentralized computing layer and building a decentralized cloud ecosystem.
Crust contains 3 major layers:
1. GPoS (Guaranteed Proof of Stake) consensus layer. GPoS consensus uses storage resources as a guarantee. It encourages nodes to provide more storage resources, and improves the security and robustness of the network.
2. MPoW (Meaningful Proof of Work) layer. Based on the Trusted Execution Environment (TEE) technology, MPoW mechanism quantifies storage resource usage …

Crust Network

---

README.md
rfp-proposal/proposal-template.md

RFP proposal

---

grants/speculative/polkascan_signer_interfaces.md

###
This project extends the Polkascan stack in general and extends Polkascan's Python libraries in particular with signing and signature verification capabilities by supporting two key methods for integrating with external signers. 1) Python Subkey Interface: for offline signing and signature verification. 2) Parity Signer Interface: for secure online signing. Our fourth wave grant work left signing capabilities off-scope in our Python libraries. This project aims to provide full signing capabilities that can be used from within Python libraries and from user-facing Angular (web) applications.

Polkascan Signer Interfaces Grant Application

---

grants/speculative/web3_analytics.md

###
Web3 Analytics is a decentralized Google Analytics alternative aiming to give users the full control of their data. It provides web performance measurement, customized statistics, and data visualization dashboard. With the power of TEE (Phala.Network, the confidential contract protocol shared with another W3F grant project pLIBRA), users' personal data are kept secretly and can only be used in an approved way. As a result, users literally get the 100% control of their data.

Web3 Analytics: a decentralized Google Analytics alternative

---

grants/polkadot_stack.md

- chaos testing frameworks
- fuzzy testing frameworks
- validator payout automatisation
- news/media fakt checking systems
- public voting systems
- ipfs module connectors for substrate
arranges existing projects in tables to show the current state alpha, beta, general availability including the possibility to track the current up to date version in the future

polkadot stack md update

---

grants/rfps/assemblyscript-runtime.md

###
The grant application is a proposal for what would be the most reasonable plan for developing/supporting AssemblyScript Runtimes as per LimeChain's understanding.
- [] The "Development Roadmap" section in the application has an estimate of funds required.

PoC Account-Based AssemblyScript Runtime

---

grants/speculative/Subsocial-2.md

###
Subsocial is a set of Substrate pallets with web UI that allows anyone to launch their own decentralized censorship-resistant social network aka community. Every community can be a separate Substrate chain and connect with other communities via a Polkadot-based relay chain.
You can think of this as decentralized versions of Reddit, Stack Exchange or Medium, where subreddits or communities of Stack Exchange or blogs on Medium run on their own chain. At the same time, users of these decentralized communities should be able to share their reputation or transfer coins and other values from one community to another via Polkadot relay chain.
To learn more about Subsocial, please visit [Subsocial …

Subsocial. Chapter 2

---

grants/speculative/open_square_network.md

###
Open Square Network is a blockchain based crowdsourcing and reputation platform. It will be implemented as a para-chain
of Polkadot. We aim to attract thousands of middle and small sized enterprises and millions of developers in China for the first phase. This platform is a trial to evolve the human resource market. First phase features include:
- Bounty funders can fund a bounty, while hunters can apply it.
- Funders can get mining power by successful collaboration with hunters.
- Reputation of both funders and hunters will be calculated based on the finished bounty and remarks.
- Aim to maintain relatively long collaboration between bounty funders and hunters.
- Platform fairness and transparency will be provided by …

Open Square Network - BlockChain Based Crowdsourcing and Reputation Platform

---

rfp-proposal/appi.md

RFP proposal for auto-funded public infrastructure for Kusama and Polkadot.

APPI: Auto-funded public p2p infrastructure

---

grants/rfps/appi.md

###
Auto-funded public p2p infrastructure 
(APPI) for the Polkadot and, specifically, Kusama ecosystem.
The idea is to incentivize people to run full and archive nodes at home,
without relying on cloud servers and centralized points of failure.

Appi - Vedar

---

grants/speculative/subscan_grant_application.md

Subscan grant application

---

grants/speculative/t3rn.md

###
This is the application regarding the initial phase of work on the interoperable t3rn protocol - standalone Gateway. 
The standalone Gateway pallet for multi-steps transaction processing that brings a possibility of safely reverting the changes based on external of parachain factors and spread over time. The standalone version of the gateway brings additional phases over the regular runtime execution - commit and revert, due to which effects of the execution can be reverted and never committed to the target accounts.
In the following development phases, t3rn is designed to be a protocol for interoperable code execution between multiple blockchains, which makes it safe, simple and reversible. The protocol offers the …

Standalone Gateway as the initial phase of t3rn - a protocol for interoperability

---

grants/speculative/polkassembly_grant_application.md

###
Polkassembly is a platform for anyone to discover and participate in Polkadot and Kusama governance. You can browse proposals made on chain, discuss with the community and vote directly from the website using a browser extension. Proposal authors are the only one able to edit the proposal post and description.

Added polkassembly grant application

---

grants/speculative/swift_api.md

###
Swift API is a library that allows interacting with Polkadot/Substrate from Swift code - the main programming language for Apple ecosystem, effectively enabling Polkadot/Substrate developers to create native iOS and Mac applications.

Added proposal for Swift API

---

grants/speculative/Cosmos_SDK_parachain_development_kit_Phase_2.md

###
We are going to build the functionality that allows anyone who has built a chain with the Cosmos SDK to turn this chain into a full Polkadot parachain. The purpose here is that any sovereign chain created with the Cosmos SDK could connect with Polkadot and not be responsible for their own security.

Cosmos SDK Parachain development kit

---

grants/speculative/financial_pallet.md

###
[Financial pallet](https://github.com/equilibrium-eosdt/equilibrium-financial-pallet) provides means to calculate various statistical measures of users' crypto asset portfolios for the purposes
of risk calculations and financial modeling.
- It gathers prices from price oracle
- It calculates returns
- It calculates volatilities and correlations
- It calculates portfolio risk
- It calculates Value at Risk measure

Application

---

grants/speculative/nuclei_governance_os.md

###
> This project could be a part of the `Public Voting System - Open Government and E-Participation Web Software` section on the Polakdot Stack.
This project covers the development of governance / organizations focused pallets. One of the use cases for it could be to manage cities or public structures in an open manner which is why I think it could be linked to the Open Government section of the stack.
I hope to be able to take this further via a complete suite / dashboard after this grant.

grant application for the governance OS (Nuclei Studio OÜ)

---

grants/grant-badge-guidelines.md

Fixed email address to grants@web3.foundation

Email address typo

---

grants/grants.md

* Fix link

---

grants/speculative/nsure_network.md

###
Nsure is an open insurance platform for Open Finance. The project borrows the idea of Lloyd’s London, a market place to trade insurance risks, where premiums are determined by a Dynamic Pricing Model. Capital mining will be implemented to secure capital required to back the risks at any point of time. A 3-phase crowd voting mechanism is used to ensure every claim is handled professionally.
The project here is a branch for Polkadot, the original ethereum version which is published here: https://github.com/nsure-tech/

add nsure.network grant

---

rfp-proposal/identity-directory.md
rfp-proposal/php-api.md
rfp-proposal/php-scale.md

PHP is extremely popular. It makes no sense to not have a library for communicating with Substrate from it.

PHP Scale Codec and API RFP

---

grants/grant-badge-guidelines.md

- Removing unnecessary newlines
- stricter language
- more structure (taken from email template)
Do we need someone from legal to review this?

Clarifying use of the badge

---

rfps/xcm-tool.md

XCM is an essential component to all the parachains. There are still a few missing pieces and it will be helpful if W3F is able grant some team is to complete this puzzle.

Adding RFP for XCM library & tools

---

rfps/candle-auction.md

Candle auctions should be available via a simple smart contract, not just used for parachain slot allocation
See RFP

create an rfp for candle auction contract

---

rfps/staking-rewards-collector-front-end.md
rfps/suggestion-template.md

This application is:
This application is:
The [staking-rewards-collector](https://github.com/w3f/staking-rewards-collector) is a tool to gather staking rewards for given addresses and cross-reference those with daily price data. This is a very useful tool for every validator and nominator in the ecosystem. However, since it has currently a CLI and requires some technical knowledge to set up (git, nodejs, yarn). A front-end hosted on a website could help many users getting access to this tool and enjoy the benefits.
The backend is already written in javascript, this should make it quite easy to host as a website and develope a front-end.
The application:

Staking rewards collector front end

---

grants/accepted_grant_applications.md

Update Subgame link to our official website
This application is:
This application is:
> Provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous one, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
>
> The details should be in the application document that is being added to the repository via this pull request.
The application:

Update Subgame link to our official website

---

grants/accepted_grant_applications.md

Update please the link to the Robonomics project website

Change website link for Robonomics

---

grants/milestone-deliverables-guidelines.md

see also w3f/Grant-Milestone-Delivery/pull/210

Replace invoice form with generalised one
